title: Postgres Tutorial
description: Postgres Tutorial
baseurl: "/postgres-tutorial"
url: "https://renece153.github.io"
remote_theme: pages-themes/primer@v0.6.0

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

author:
  name: Rey Torrecampo
  email: rentorrecampoece153@gmail.com

social:
  linkedin: https://www.linkedin.com/in/rey-lawrence-torrecampo-ece/
  github: https://github.com/renece153
  website: https://renece153.github.io/portfolio/

# Navigation (manual)
nav:
  - title: Home
    url: /
  - title: Chapter 4.1 — RDBMS
    url: /page2.md
  - title: PostgreSQL Introduction
    url: /postgres-intro
  - title: CRUD Basics
    url: /crud-basics
